Mode: 'Area'
Lobby:
  Rank:
Area:
  Name:
    - 'Area'
  advance: 0.5
  maxSpeeder: 1
  maxHunter: 4
  Speeder:
    Kill: 200
    Death: 100
    Advancement: 100
  Hunter:
    Kill: 75
    Death: 50
    Advancement: 75
    ReviveCooldown(tick): 60
  Totem_of_Undying: true
Datebase:
