# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile Minecraft Spigot or Paper (BuildTools)
        # You may pin to the exact commit or the version.
        # uses: SpraxDev/Action-SpigotMC@4d6b6af2701066885f12ec42607712ba0782cadd
        uses: actions/checkout@v2
        with:
          # Versions to build (sperate multiple with ',')
          versions: latest # optional, default is latest
          # Should sources be generated?
          generateSrc: false # optional, default is false
          # Should the documentation be generated?
          generateDoc: false # optional, default is false
          # Should we disable the BuildTools's Java-Version-Check
          disableJavaCheck: false # optional, default is false
          # Disables the check for existing files in the local maven repository
          forceRun: false # optional, default is false
          # The amount of builds allowed to run at a time, set to '-1' to use system's cpu count
          threads: -1 # optional, default is -1
          # Whose BuildTool should be used? (SpigotMC [default], SpraxDev)
          buildToolProvider: SpigotMC # optional, default is SpigotMC
